baseurl = "https://www.kranzky.com/"
languageCode = "en-us"
title = "Jason Hutchens"
theme = "prologue"

[params]
  name = "Jason Hutchens"
  description = "(aka Lloyd Kranzky)"

[[params.social]]
  medium = "medium"
  icon = "medium"
  link = "https://blog.kranzky.com"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/kranzky"

[[params.social]]
  medium = "stackoverflow"
  icon = "stack-overflow"
  link = "https://stackoverflow.com/users/5442/kranzky?tab=profile"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/jasonhutchens"

[[params.social]]
  medium = "youtube"
  icon = "youtube"
  link = "https://www.youtube.com/channel/UC5fbLdfUtTaHpL2qbQtW2rg"

# row 1

[[params.projects1]]
  title = "Sesame"
  alt = "The simple password solution for everybody."
  source = "img/portfolio/sesame.png"
  url = "https://sesame.website"

[[params.projects2]]
  title = "MegaHAL"
  alt = "A learning chatterbot."
  source = "img/portfolio/megahal.png"
  url = "https://rubygems.org/gems/megahal"

[[params.projects3]]
  title = "Canard"
  alt = "A not-quite-proof-of-concept implementation of QDD."
  source = "img/portfolio/canard.png"
  url = "https://blog.kranzky.com/tdd-is-canard-tell-it-to-the-duck-207b1d574f23"

# row 2

[[params.projects1]]
  title = "Corona"
  alt = "Charts, SVG badges, CSV export and JSON API for the Johns Hopkins CSSE Coronavirus / COVID-19 dataset."
  source = "img/portfolio/corona.png"
  url = "https://corona.kranzky.com/"

[[params.projects2]]
  title = "Le Word Bot"
  alt = "Just a bot solving the daily wordle."
  source = "img/portfolio/wordle.png"
  url = "https://twitter.com/lewordbot"

[[params.projects3]]
  title = "rnDB"
  alt = "A procedurally generated database of everyday things."
  source = "img/portfolio/rndb.png"
  url = "https://blog.kranzky.com/the-case-of-the-fake-database-7bde487213a3"

# row 3


[[params.projects1]]
  title = "Gravitas"
  alt = "A local multiplayer 'cave flyer' party game"
  source = "img/portfolio/gravitas.png"
  url = "https://thepunkcollective.itch.io/gravitas"

[[params.projects2]]
  title = "Insoluble"
  alt = "A machine-generated novel for NaNoGenMo."
  source = "img/portfolio/insoluble.png"
  url = "https://github.com/kranzky/insoluble/blob/master/README.md"

[[params.projects3]]
  title = "FAQoverflow"
  alt = "Great answers to interesting questions about everything"
  source = "img/portfolio/faqoverflow.png"
  url = "http://faqoverflow.kranzky.com"

# row 4

[[params.projects1]]
  title = "Statistical Me"
  alt = "Discover how unique you really are."
  source = "img/portfolio/statistical.png"
  url = "https://statistical-me.kranzky.com"

[[params.projects2]]
  title = "d-Board"
  alt = "A novel text input method for use with game controllers."
  source = "img/portfolio/dboard.png"
  url = "https://www.youtube.com/watch?v=Do0fUWME0Mw"

[[params.projects3]]
  title = "BLaTTiX"
  alt = "A fast-paced retro 2.5D dual-stick arena shooter."
  source = "img/portfolio/blattix.gif"
  url = "https://thepunkcollective.itch.io/blattix"

# row 5

[[params.projects1]]
  title = "hackTILE"
  alt = "A cellular automata game engine."
  source = "img/portfolio/hacktile.gif"
  url = "https://www.youtube.com/watch?v=uxfEw5C3R18"

[[params.projects2]]
  title = "Laggy Dash"
  alt = "A massively single-player infinite runner."
  source = "img/portfolio/laggydash.jpg"
  url = "http://laggydash.kranzky.com/"

[[params.projects3]]
  title = "Nosedive"
  alt = "Use your black mirror to rate all the things."
  source = "img/portfolio/nosedive.png"
  url = "https://nosedive.kranzky.com/"

# row 6

[[params.projects1]]
  title = "Aruma Room"
  alt = "Control light and music with your hands."
  source = "img/portfolio/arumaroom.png"
  url = "https://github.com/kranzky/arumaroom"

[[params.projects2]]
  title = "National Eyeball"
  alt = "An Australia-wide visualisation of government data."
  source = "img/portfolio/eyeball.png"
  url = "https://github.com/kranzky/national_eyeball"

[[params.projects3]]
  title = "RockVomit"
  alt = "A ragdol rhythym action game made for #GGJ17."
  source = "img/portfolio/rockvomit.png"
  url = "https://github.com/rocket-hands/rockvomit"

# row 7

[[params.projects1]]
  title = "Bogus Quest"
  alt = "A game of deception."
  source = "img/portfolio/bogus_quest.png"
  url = "https://github.com/kranzky/bogus_quest"

[[params.projects2]]
  title = "Dwarf Squad"
  alt = "Four dwarves, one controller."
  source = "img/portfolio/dwarfsquad.jpg"
  url = "https://github.com/ggj14/dwarf-squad"

[[params.projects3]]
  title = "Brown Cloud"
  alt = "Build a single brown cloud by collecting and spitting clouds of different colours."
  source = "img/portfolio/browncloud.jpg"
  url = "https://github.com/kranzky/brown_cloud"

# row 8

[[params.projects1]]
  title = "Quantum Light Cycles"
  alt = "An entry to the one-key / one-switch comp on Retro Remakes."
  source = "img/portfolio/qlc.gif"
  url = "https://github.com/kranzky/quantum_light_cycles"

[[params.projects2]]
  title = "Refrax"
  alt = "A game inspired by the pause mode of Jeff Minter's Iridis Alpha."
  source = "img/portfolio/refrax.png"
  url = "https://github.com/kranzky/refrax"

[[params.projects3]]
  title = "Soduku Sweeper"
  alt = "xxx."
  source = "img/portfolio/sweeper.png"
  url = "https://github.com/kranzky/soduku_sweeper"

# row 9

[[params.projects1]]
  title = "Black & White"
  alt = "Black & White is a god video game developed by Lionhead Studios."
  source = "img/portfolio/black.png"
  url = "https://www.youtube.com/watch?v=dm2kTfwT9HU"

[[params.projects2]]
  title = "L.A. Noire"
  alt = "L.A. Noire is a neo-noir detective action-adventure video game developed by Team Bondi."
  source = "img/portfolio/noire.png"
  url = "https://www.youtube.com/watch?v=xk69qfTRIgY"

[[params.projects3]]
  title = "Interzone Futebol"
  alt = "Interzone Futebol is a massively multiplayer online game centered on futebol."
  source = "img/portfolio/interzone.png"
  url = "https://www.youtube.com/watch?v=wLFdv561Flo"
